repos:
#  - name: gitops
#    repoURL: ssh://git@localhost:10022/stefan/gitops.git
#    path: /
#    branch: master

#  - name: dummy-pod
#    repoURL: ssh://git@localhost:10022/stefan/dummy-pod.git
#    path: pods
#    branch: master

  - name: flask-app
    repoURL: https://github.com/stefan-bergstein/edge-lab.git
    path: flask-webservice
    branch: master

  - name: blog-django
    repoURL: https://github.com/stefan-bergstein/edge-lab.git
    path: blog-django
    branch: master

# test
#repoDir: /root/repos

# dev 
repoDir: /home/sbergste/Projects/try-podman/python/repos/


### baseDir: test-gitops


