
bases:
- github.com/stefan-bergstein/edge-lab/blog-django?ref=519f3bcbf2fc9a5311ff4d4fab2e33b8c9c30520
resources:
#- bullshit.yaml
- blog-django-route.yaml
patchesStrategicMerge:
#- allinone.yaml
- blog-django-deployment.yaml
#configMapGenerator:	
#- name: the-map	
#  literals:	
#    - altGreeting="$(ALT_GREETING)"
#    - enableRisky="false"
#secretGenerator:
#- name: the-secret
#  literals:
#    - FRUIT=apple#

#vars:
#- name: ALT_GREETING
#  objref:
#    kind: Deployment
#    name: openshift-blog
#    apiVersion: apps/v1
#  fieldref:
#    fieldpath: spec.replicas