#
# Run blog-django as pod in podman
#

apiVersion: v1
kind: Pod
metadata:
  name: podman-blog
  labels:
    app: podman-blog

spec:
  containers:
  - name: blog-from-image-pod-container
    image: openshiftkatacoda/blog-django-py
    ports:
    - containerPort: 8080
      hostPort: 9090
      protocol: TCP
    workingDir: /opt/app-root/src

